### ISSUE TITLE
Complete end-to-end deposit flow

### ISSUE THREAD

**Issue by msfeldstein** [stellar-deprecated/transfer-server-validator#16]
Now that we can interact with interactive flows, lets get a full e2e run of deposit tested

**Comment by JakeUrban** [comment]
We have one that works locally but the selenium driver appears to fail when deployed. See #45

**Comment by JakeUrban** [comment]
Getting an E2E _deposit_ flow is going to be hard to generalize for all anchors, since anchors have to poll their unique rails for a deposit made by the user. I'm not sure how we would mock this.

However, I think it'd be a lot easier to do E2E for _withdrawal_ transactions. Once the interactive flow has completed, the test can submit the transaction to the stellar network just like the wallet would. Anchor's would then detect the transaction has completed (since they are presumably streaming transactions to/from their stellar accounts like Polaris) and mark the transaction as complete.

Do we want to find a way to get an E2E deposit test or should we just change this issue to be for withdraw?

**Comment by msfeldstein** [comment]
Anchors should auto-approve deposits on testnet right?  There's going to be way more complicated problems when we start to run this on mainnet

**Comment by JakeUrban** [comment]
Thats true, we could expect them to auto-approve it and fail a test if it doesn't move from `pending_user_transfer_start` to `complete` within a timeframe?

There are a lot of problems with what we have now if we want to run it on mainnet, all stemming from the fact that we'd be working with real money. Friendbot calls wouldn't be available, anchors wouldn't go through E2E flows without us sending them real money for the deposit, etc. We may just have to settle with a fraction of the test coverage on mainnet.

**Comment by JakeUrban** [comment]
This has been completed for testnet deployments
