### ISSUE TITLE
Test for Claimable Balance Support

### ISSUE THREAD

**Issue by Zagan202** [stellar-deprecated/transfer-server-validator#184]

**Comment by Zagan202** [comment]
1. Write and `xit` (skip completely) CB tests for SEP6 and SEP24 suite
2. Once rollout begins make tests optional and and update/extend tests where appropriate.
3. Once SEP6 SEP24 are live on https://github.com/stellar/stellar-protocol main branch, CB test become mandatory.

**Comment by JakeUrban** [comment]
Unfortunately we cannot test support for CBs with SEP-24 since it requests the validator to complete an interactive flow, which is cannot do. We could support it in the SEP-6 suite, but testing SEP-6 implementations requires the validator to know what values are accepted for custom fields in described in their `/info` endpoints, which is a separate problem. Closing this until we figure out how to create transactions via SEP-6 in an automated fashion without hard-coding values per-anchor.
